# One in a quadrillion


Donald Cicchetti, an independent contractor and PhD economist from Berkeley supplied an analysis that was included in several lawsuits, including the Supreme Court action brought by the state of Texas against Pennsylvania. His conclusions were featured in many public statements from Trump supporters including tweets from the Trump press secretary.  Cicchetti completed three different analyses: comparing Biden's share of the two party vote in Georgia to that of Clinton (in 2016), comparing early vote totals in battleground states to later vote totals, comparing the rejection of ballots in Georgia in 2016 to that of 2020, and an analysis of absentee ballots in Wayne County, MI.

## Clinton and Biden in Georgia
Biden did better in Georgia than Clinton did in 2016. 



```{r clinton, echo=F}
Clinton = data.frame(Candidate=c('Clinton','Trump'),Votes=c(1877963,2089104),Pct=c(.459,.510))
Biden = data.frame(Candidate=c('Biden','Trump'),Votes=c(2474507,2461837),Pct=c(.495,.493))
kable(list(Clinton,Biden))%>% kable_styling()
```

Cicchetti argues that it is statistically impossible that Biden's percentage of the vote should be 3.6\% greater thatn that of Clinton.   The argument he gives is known as a hypothesis test.  Statistics 101 students know it as the two-proportion Z-test and indeed the section in Cicchetti's brief is called "Z-Scores for Georgia".  In a hypothesis test, one first constructs a "null hypothesis" and then uses the data to see whether the "null hypothesis" is plausible. In this case, the framework for the hypothesis test asssumes that we have samples from two different populations and are observing the proportion of each sample that has a given characteristic. In this case, our samples are clearly the actual voters of 2016 and 2020 respectively and the proportions are the percentages of votes voting for the Democratic candidate (45.9\% and 49.5\% respectively). The null hypothesis assumes that each sample is from a population and that the relavant proportion of each population is identical. In this case, the null hypothesis is that the proportion of all possible voters in 2016 who would vote demcratic is identical to the proportion of all possible voters in 2020 who would vote democratic.  One then computes a number, called the $p$-value (less than 1 in a quadrillion in this example).  The $p$-value is interpreted this way:
if indeed the two populations have identical proportions of people who would vote democratic, the probability that Biden's actual percentages would be so different is less than 1 in a quadrillion.  Cicchetti finds this compelling evidence of fraud.

It is easy on its face to see why, though Cicchetti computation might be right, it is entirely unsurprising. We have no reason to suppose that the populations of 2016 possible voters and 2020 possible voters are identical.  First, they are not the same voters. Some voters dropped off the rolls and many more were added (over a million). Second, there is no reason to suppose that Clinton's popularity in the 2016  population is the same as the Biden popularity in the 2020 population.  Biden was a more popular candidate than Clinton in almost every state.  The conclusion of the hypothesis test is pedestrian - the popularity of Biden and Clinton are different. 

Though any Statistics 101 student knows that the Cicchetti aa quadrillion (and is very small in the other three as well). rgument is flawed, there is a common sense way of seeing Cichetti's mistake.  
Cicchetti's hypothesis test can be applied to any state.  And it turns out, in 48 of the 51 contests, the $p$-value is less than 1 in a trillion, Another way of saying this is that Biden's popularity in no state was exactly the same as Clinton's.  We would have been amazed to find out otherwise! Essentially, Cicchetti should make exactly the same argument for any state and argue that the results in any state, even those in which Trump did better than 2016, are not to be trusted.    In fact, Cicchetti's argument can be used to show that no election can be believed. Based on the 2012 election results, the 2016 election results cannot be believed.  Trump could not have done as well as he did.

In the end, we run elections because we know that things might turn out differently than four years ago.  And we shouldn't be surprised when they do.  


## Early and Late Tabulation in Georgia

Biden got a larger share of the votes tabulated later in the count than earlier. 


